//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetBanks.RuleBaseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bank", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Bank : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranslatorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BanknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TranslatorType {
            get {
                return this.TranslatorTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslatorTypeField, value) != true)) {
                    this.TranslatorTypeField = value;
                    this.RaisePropertyChanged("TranslatorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Bankname {
            get {
                return this.BanknameField;
            }
            set {
                if ((object.ReferenceEquals(this.BanknameField, value) != true)) {
                    this.BanknameField = value;
                    this.RaisePropertyChanged("Bankname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Exchange {
            get {
                return this.ExchangeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeField, value) != true)) {
                    this.ExchangeField = value;
                    this.RaisePropertyChanged("Exchange");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RuleBaseService.RuleBaseSoap")]
    public interface RuleBaseSoap {
        
        // CODEGEN: Generating message contract since element name GetBanksResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBanks", ReplyAction="*")]
        GetBanks.RuleBaseService.GetBanksResponse GetBanks(GetBanks.RuleBaseService.GetBanksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBanks", ReplyAction="*")]
        System.Threading.Tasks.Task<GetBanks.RuleBaseService.GetBanksResponse> GetBanksAsync(GetBanks.RuleBaseService.GetBanksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBanksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBanks", Namespace="http://tempuri.org/", Order=0)]
        public GetBanks.RuleBaseService.GetBanksRequestBody Body;
        
        public GetBanksRequest() {
        }
        
        public GetBanksRequest(GetBanks.RuleBaseService.GetBanksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBanksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int creditScore;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int duration;
        
        public GetBanksRequestBody() {
        }
        
        public GetBanksRequestBody(int creditScore, double amount, int duration) {
            this.creditScore = creditScore;
            this.amount = amount;
            this.duration = duration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBanksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBanksResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetBanks.RuleBaseService.GetBanksResponseBody Body;
        
        public GetBanksResponse() {
        }
        
        public GetBanksResponse(GetBanks.RuleBaseService.GetBanksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBanksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GetBanks.RuleBaseService.Bank[] GetBanksResult;
        
        public GetBanksResponseBody() {
        }
        
        public GetBanksResponseBody(GetBanks.RuleBaseService.Bank[] GetBanksResult) {
            this.GetBanksResult = GetBanksResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RuleBaseSoapChannel : GetBanks.RuleBaseService.RuleBaseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RuleBaseSoapClient : System.ServiceModel.ClientBase<GetBanks.RuleBaseService.RuleBaseSoap>, GetBanks.RuleBaseService.RuleBaseSoap {
        
        public RuleBaseSoapClient() {
        }
        
        public RuleBaseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RuleBaseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleBaseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleBaseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetBanks.RuleBaseService.GetBanksResponse GetBanks.RuleBaseService.RuleBaseSoap.GetBanks(GetBanks.RuleBaseService.GetBanksRequest request) {
            return base.Channel.GetBanks(request);
        }
        
        public GetBanks.RuleBaseService.Bank[] GetBanks(int creditScore, double amount, int duration) {
            GetBanks.RuleBaseService.GetBanksRequest inValue = new GetBanks.RuleBaseService.GetBanksRequest();
            inValue.Body = new GetBanks.RuleBaseService.GetBanksRequestBody();
            inValue.Body.creditScore = creditScore;
            inValue.Body.amount = amount;
            inValue.Body.duration = duration;
            GetBanks.RuleBaseService.GetBanksResponse retVal = ((GetBanks.RuleBaseService.RuleBaseSoap)(this)).GetBanks(inValue);
            return retVal.Body.GetBanksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetBanks.RuleBaseService.GetBanksResponse> GetBanks.RuleBaseService.RuleBaseSoap.GetBanksAsync(GetBanks.RuleBaseService.GetBanksRequest request) {
            return base.Channel.GetBanksAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetBanks.RuleBaseService.GetBanksResponse> GetBanksAsync(int creditScore, double amount, int duration) {
            GetBanks.RuleBaseService.GetBanksRequest inValue = new GetBanks.RuleBaseService.GetBanksRequest();
            inValue.Body = new GetBanks.RuleBaseService.GetBanksRequestBody();
            inValue.Body.creditScore = creditScore;
            inValue.Body.amount = amount;
            inValue.Body.duration = duration;
            return ((GetBanks.RuleBaseService.RuleBaseSoap)(this)).GetBanksAsync(inValue);
        }
    }
}
